### PR TITLE
Improve waitFor framework. Introduce a PropertyKeyOf<T> utility type for safely objectifying types into a (keyof T)[].

### PR DESCRIPTION
**Pull request by DeFixAndEr**
Move liquidationInfo `Dependencies[]` within waitForLiquidations to liquidations slice.
This has the following 2 benefits:
1. it co-locates the dependencies to each slice;
2. it ensures the resultant string[] is isomorphic to U(keyof liquidArgs).

Downside: 
1. the boilerplate which discretizes the type into an object.

### CODE REVIEW

**Comment by iwantausernamewithoutnumbers** [comment]
Played with this concept a little bit:

```
export const dependencyBuilder = <Deps extends readonly string[]>(deps: Deps): <Args extends {[Key in Deps[number]]: any}>() => Deps => {
  return () => (deps)
}

interface Args {
  itemOne: boolean,
  itemTwo: number,
  itemThree: string
}
const deps = dependencyBuilder(["itemOne", "itemTwo", "itemThree"] as const)<Args>();
```

In this case, `deps` is inferred to be `readonly ["itemOne", "itemTwo", "itemThree"]`

Downsides:
1. `Args is unused` tslint warning
2.  Typescript only validates that `Args` contains all keys in `Deps` - not the other way around.
3.  Relies on function currying to work around typescript generic limitations - (as we want to infer dependency list, but define Args interface).
4.  Dependency list needs `as const` for return type correctness - clunky.

**Comment by DeFixAndEr** [comment]
> Typescript only validates that Args contains all keys in Deps - not the other way around.
Though the intermediary "PropertyKey" object is verbose, this checks that all keys of Deps are equivalent to the keys of Args. This means the type checker will catch if either a key is missing or is incorrect.

**Comment by br4e** [comment]
lgtm! did you get a chance to take a look at @iwantausernamewithoutnumbers 's changes?

**Comment by DeFixAndEr** [comment]
Yep! It's a cool use of interface extensions! The 2nd downside is the thing we're trying to address. We want to ensure that the returned array is exactly `["itemOne", "itemTwo", "itemThree"]`, but ["itemOne", "itemThree"] is valid for `dependencyBuilder` terms of the type matcher.

```
type Args = {
  itemOne: boolean,
  itemTwo: number,
  itemThree: string
}
```

We might be able to avoid specifying the object with his approach. I'll try adapting to specify a validated array instead of an explicit object.

**Comment by br4e** [comment]
Lets close this in favor of the new waitfor framework, it's committed to master

**Pull request closed without merging**
